AWSTemplateFormatVersion: 2010-09-09

Description: Criacao do AppRunner.

Resources:

  IAMAppRunner:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ROLE-APPRUNNER
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "build.apprunner.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: POLICY-APPRUNNER
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                  - "ecr:DescribeImages"
                  - "ecr:GetAuthorizationToken"
                  - "ecr:BatchCheckLayerAvailability"
                Resource: "*"

  IAMTaskAppRunner:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ROLE-TASK-APPRUNNER
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "tasks.apprunner.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: POLICY-TASK-APPRUNNER
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "s3:GetObject"
                  - "s3:ListAllMyBuckets"
                Resource: "*"

  EndpointAppRunner:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.apprunner.requests
      PrivateDnsEnabled: false
      SecurityGroupIds: 
        - sg-066d9f1a7388308da
      SubnetIds: 
        - subnet-04291a330fc70dc7c
      VpcEndpointType: Interface
      VpcId: vpc-04372222deb6f3e13

  AppRunnerECR:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: DEVOPS-NA-INFRA
      SourceConfiguration: 
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt IAMAppRunner.Arn
        AutoDeploymentsEnabled: true
        ImageRepository:
          ImageIdentifier: 489732776903.dkr.ecr.us-east-1.amazonaws.com/devopsnainfra:latest
          ImageRepositoryType: ECR
          ImageConfiguration:
            Port: 80
      InstanceConfiguration:
        Cpu: 1 vCPU
        Memory: 2 GB
        InstanceRoleArn: !GetAtt IAMTaskAppRunner.Arn
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: "/"
        Timeout: 2
        Interval: 5
        UnhealthyThreshold: 5
        HealthyThreshold: 1
      NetworkConfiguration:
        IngressConfiguration:
          IsPubliclyAccessible: False

  AppRunnerPrivateEndpoint:      
    Type: AWS::AppRunner::VpcIngressConnection
    Properties:
      IngressVpcConfiguration:
        VpcEndpointId: !GetAtt EndpointAppRunner.Id
        VpcId: vpc-04372222deb6f3e13
      ServiceArn: !GetAtt AppRunnerECR.ServiceArn
      VpcIngressConnectionName: APPRUNNER-ENDPOINT