name: Deploy to App Runner 
on:
  push:
    branches: [main]

jobs:  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
          
    - name: Deploy to App Runner
      id: deploy-apprunner
      uses: awslabs/amazon-app-runner-deploy@main
      env:
        SERVER_PORT: 80
        SECRET_ENV: secret_env
      with:
        service: DEVOPS-NA-INFRA
        source-connection-arn: ${{ secrets.AWS_CONNECTION_SOURCE_ARN }}
        repo: https://github.com/${{ github.repository }}
        branch: ${{ github.ref }}
        runtime: NODEJS_16
        build-command: npm install
        start-command: npm start
        port: 80
        region: ${{ secrets.AWS_REGION }}
        cpu : 1
        memory : 2
        copy-env-vars: |
          SERVER_PORT
        copy-secret-env-vars: |
          SECRET_ENV
      
    - name: App Runner URL
      run: echo "App runner URL ${{ steps.deploy-apprunner.outputs.service-url }}" 